### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by levinsonmm** [levinsonmm/MI-449-SS17-741-html-more-kinds-of-content-OSB7Pe#1]
@chrisvfritz Can you take a look at this? It's [hosted here](https://levinsonmm.github.io/MI-449-SS17-741-html-more-kinds-of-content-OSB7Pe/) and meets the following criteria:

- [x] Include [a haiku](http://www.kidzone.ws/poetry/haiku.htm), describing the feelings this product will evoke (with `br` elements to add new lines where appropriate)
- [x] [Create and download a sound effect file](http://sfbgames.com/chiptone/) for what the game will sound like when you win, then include an audio player in the page so users can hear the sample
- [x] Include a table comparing which features your game has in comparison to competitors (these competitors may be real or made up)
- [x] Include a demo video from YouTube, but featuring a completely unrelated animal being cute (not getting hurt!)

**Comment by chrisvfritz** [comment]
Looks great! 🎉  I always like to find _some_ room for improvement, but you made me really work for it this time. 😄  On [this line](https://github.com/levinsonmm/MI-449-SS17-741-html-more-kinds-of-content-OSB7Pe/blob/master/index.html#L42), I see an empty line before the closing `</body>`, which would be fine if you also included an empty line after the opening `<body>` tag, but I would have an empty line in both places or neither for consistency.

**Comment by levinsonmm** [comment]
I just fixed that up! Thanks for the feedback. 😄

**Comment by chrisvfritz** [comment]
Excellent! Even the commit message was nice and descriptive. 🎆 😸 🏎  👍 🎈 🚀 :shipit:
